name: Flutter CI/CD for iOS

on:
  push:
    branches:
      - main  # Or your default branch name
  pull_request:
    branches:
      - main  # Or your default branch name

jobs:
  build:
    runs-on: macos-latest  # Using a macOS runner to build for iOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'  # Specify the version you want to use

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Build iOS release
        run: |
          flutter build ios --release

      - name: Upload release .ipa file
        uses: actions/upload-artifact@v2
        with:
          name: ios-release
          path: build/ios/ipa/*.ipa